#!/bin/bash
##vim configuration

/etc/vim/vimrc
" All system-wide defaults are set in $VIMRUNTIME/debian.vim and sourced by
" the call to :runtime you can find below.  If you wish to change any of those
" settings, you should do it in this file (/etc/vim/vimrc), since debian.vim
" will be overwritten everytime an upgrade of the vim packages is performed.
" It is recommended to make changes after sourcing debian.vim since it alters
" the value of the 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Vim will load $VIMRUNTIME/defaults.vim if the user does not have a vimrc.
" This happens after /etc/vim/vimrc(.local) are loaded, so it will override
" any settings in these files.
" If you don't want that to happen, uncomment the below line to prevent
" defaults.vim from being loaded.
" let g:skip_defaults_vim = 1

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

"添加by jdm
" 设置当文件被改动时自动载入
 set autoread
" "允许插件  
 filetype plugin on
" "共享剪贴板  
" "从不备份  
 set nobackup
" "make 运行
" "自动保存
 set autowrite
 set ruler                   " 打开状态栏标尺
 set cursorline              " 突出显示当前行
 set magic                   " 设置魔术
" " 设置在状态行显示的信息
 set foldenable              " 开始折叠
" " 不要使用vi的键盘模式，而是vim自己的
 set nocompatible
" 语法高亮
" " 去掉输入错误的提示声音
 set noeb
" " 在处理未保存或只读文件的时候，弹出确认
 set confirm
" " 自动缩进
 set autoindent
 set cindent
" " Tab键的宽度
 set tabstop=4
" " 统一缩进为4
 set softtabstop=4
 set shiftwidth=4
" " 不要用空格代替制表符
 set noexpandtab
" " 在行和段开始处使用制表符
 set smarttab
" " 显示行号
 set number
" " 历史记录数
 set history=1000
" "禁止生成临时文件
 set nobackup
 set noswapfile
" "搜索忽略大小写
 set ignorecase
" "搜索逐字符高亮
 set hlsearch
 set incsearch
" "行内替换
 set gdefault
 "编码设置
 "set enc=utf-8
 "set fencs=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936
 ""语言设置
 set langmenu=zh_CN.UTF-8
 set helplang=cn
 " 我的状态行显示的内容（包括文件类型和解码）
  set laststatus=2
 " " 命令行（在状态行下）的高度，默认为1，这里是2
  set cmdheight=2
 " " 侦测文件类型
  filetype on
 " " 载入文件类型插件
  filetype plugin on
 " " 为特定文件类型载入相关缩进文件
  filetype indent on
 " " 保存全局变量
  set viminfo+=!
 " " 字符间插入的像素行数目
  set linespace=0
 " " 增强模式中的命令行自动完成操作
  set wildmenu
  " 使回格键（backspace）正常处理indent, eol, start等
 set backspace=2
  " " 允许backspace和光标键跨越行边界
 set whichwrap+=<,>,h,l
  " " 可以在buffer的任何地方使用鼠标（类似office中在工作区双击鼠标定位）
 set mouse=a
 set selection=exclusive
 set selectmode=mouse,key
  " " 通过使用: commands命令，告诉我们文件的哪一行被改变过
 set report=0
  " " 在被分割的窗口间显示空白，便于阅读
 set fillchars=vert:\ ,stl:\ ,stlnc:\
  " " 高亮显示匹配的括号
 set showmatch
  " " 匹配括号高亮的时间（单位是十分之一秒）
 set matchtime=1
  " " 光标移动到buffer的顶部和底部时保持3行距离
 set scrolloff=3
  " " 为C程序提供自动缩进
 set smartindent
  " " 高亮显示普通txt文件（需要txt.vim脚本）
 au BufRead,BufNewFile *  setfiletype txt
if has('mouse') 
    set mouse-=a 
endif


" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"if has("autocmd")
"  filetype plugin indent on
"endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden		" Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

